name: Test PR Label
on:
  pull_request:
    types: ['labeled']
    branches: ['main']
  pull_request_labeled:
    - 'test-label'
    - 'another-label'
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR labeled"
