name: Test PR Label
on:
  pull_request:
    types: ['labeled']
    branches: ['main']
  pull_request_labeled:
    - 'test-label'
    - 'another-label'
jobs:
  comment-on-pr:
    runs-on: ubuntu-latest
    type: github-pr-comment
    params:
      token: ${{ secrets.GITHUB_TOKEN }}
      issue-number: ${{ github.event.pull_request.number }}
      body: "PR has been labeled"