name: Test push event

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v123'

jobs:
  test:
    name: Run on branch push
    steps:
      - run: |
          echo ${{ github.event }}
          echo TEST
      - run: |
          echo ${{ github.event }} | jq
